-- MySQL Script generated by RenovaTech
-- Fri May 17 14:00:24 2024

-- -----------------------------------------------------
-- Schema RenovaTech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RenovaTech` DEFAULT CHARACTER SET utf8 ;
USE `RenovaTech` ;

-- -----------------------------------------------------
-- Table `RenovaTech`.`tb_setor_atuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RenovaTech`.`tb_setor_atuacao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RenovaTech`.`tb_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RenovaTech`.`tb_servicos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(255) NOT NULL,
  `contato` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `setorAtuacao` VARCHAR(255) NOT NULL,
  `fk_setoratuacao_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_servicos_tb_setoratuacao_idx` (`fk_setoratuacao_id` ASC),
  CONSTRAINT `fk_tb_servicos_tb_setoratuacao`
    FOREIGN KEY (`fk_setoratuacao_id`)
    REFERENCES `RenovaTech`.`tb_setor_atuacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `RenovaTech`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RenovaTech`.`tb_cliente` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(255) NOT NULL,
  `razaoSocial` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `fk_servicos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_usuario_tb_servicos1_idx` (`fk_servicos_id` ASC),
  CONSTRAINT `fk_tb_usuario_tb_servicos1`
	FOREIGN KEY (`fk_servicos_id`)
    REFERENCES `RenovaTech`.`tb_servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


